# Generated by Django 5.2.1 on 2025-07-29 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBarbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status da Barbearia',
                'verbose_name_plural': 'Status da Barbearia',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_barbeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corte',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='corte',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
