# Generated by Django 5.2.1 on 2025-07-29 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statusbarbearia_cliente_is_barbeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
