# Generated by Django 5.2.1 on 2025-07-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_corte_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusbarbearia',
            name='domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='hora_abertura',
            field=models.TimeField(default='08:00', help_text='Horário de abertura'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='hora_fechamento',
            field=models.TimeField(default='18:00', help_text='Horário de fechamento'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='quarta',
            field=models.BooleanField(default=True, verbose_name='Quarta-feira'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='quinta',
            field=models.BooleanField(default=True, verbose_name='Quinta-feira'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='sabado',
            field=models.BooleanField(default=True, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='segunda',
            field=models.BooleanField(default=True, verbose_name='Segunda-feira'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='sexta',
            field=models.BooleanField(default=True, verbose_name='Sexta-feira'),
        ),
        migrations.AddField(
            model_name='statusbarbearia',
            name='terca',
            field=models.BooleanField(default=True, verbose_name='Terça-feira'),
        ),
    ]
